apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roboRabbitmq
  labels:
    run: roboRabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: roboRabbitmq
    spec:
      containers:
      - name: roboRabbitmq
        image: rabbitmq:latest
        imagePullPolicy: Always
        ports:
          - name: port1
            containerPort: 5672
            protocol: TCP   
