apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: robo-rabbitmq
  labels:
    run: robo-rabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: robo-rabbitmq
    spec:
      containers:
      - name: robo-rabbitmq
        image: docker/image:latest
        imagePullPolicy: Always
        ports:
          - name: port1
            containerPort: 5672
            protocol: TCP   