apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roborabbitmq
  labels:
    run: roborabbitmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: roborabbitmq
    spec:
      containers:
      - name: roborabbitmq
        image: docker/image:latest
        imagePullPolicy: Always
        ports:
          - name: port1
            containerPort: 5672
            protocol: TCP   